### ISSUE TITLE
Typo in UsageCount XML tag

### ISSUE THREAD

**Issue by keepassium** [authpass/kdbx.dart#1]
In KdbxTimes, the usage count tag is [written](https://github.com/authpass/kdbx.dart/blob/79e749b8b0b8089749ccc1c410ddd718d43d61b3/lib/src/kdbx_times.dart#L29) as `Usagecount`. It should be `UsageCount` instead, with capital "C".

As it is, other apps likely won't find the counter and this would cause issues with DB merging.

**Comment by hpoul** [comment]
good catch, seems like a typo. Although to be honest I'm not really using that right now anyway.

Is it used in Keepassium? I haven't quite found where it would get incremented.. https://github.com/keepassium/KeePassium/search?q=usagecount&unscoped_q=usagecount

**Comment by keepassium** [comment]
Yeah, I also did not take it seriously at first. I just assumed it was something to sort entries by frequency of use maybe :)

Apparently, this counter and last access/modification timestamps are required for tracking and merging changes between conflicting versions of the same database. 

In KeePassium, the usage counter is updated [here](https://github.com/keepassium/KeePassium/blob/46a3c09d8a00ebd0c82d8707ba89b9ecbd273de7/KeePassiumLib/KeePassiumLib/db/kp2/Group2.swift#L97) and [here](https://github.com/keepassium/KeePassium/blob/1cb3598b192cbb36a53000bcfbf9fa5f0ba2651b/KeePassiumLib/KeePassiumLib/db/kp2/Entry2.swift#L357). I'm not sure why GitHub does not find these lines...

**Comment by hpoul** [comment]
forgot to close that issue, fixed for a while now https://github.com/authpass/kdbx.dart/commit/f230d1a7dbd9732f238ec33104db43fbb6468cf0
Although it still is never actually increased, neither in kdbx.dart nor in [AuthPass](https://github.com/authpass/authpass/). I basically rely on the timestamps for merging 🤔️
