### ISSUE TITLE
Should we migrate from argon2_ffi to https://pub.dev/packages/dargon2_flutter?

### ISSUE THREAD

**Issue by drriguz** [authpass/kdbx.dart#9]
Hi,
I found a argon2 plugin [dargon2_flutter](https://pub.dev/packages/dargon2_flutter) that is available for all devices.
It seems to be ready to use for authpass.
Could we use it instead?

**Comment by hpoul** [comment]
Why?

**Comment by drriguz** [comment]
> Why?

I just saw a comment in https://github.com/authpass/kdbx.dart:

> For v4 argon2 support would be required. Unfortunately there are no dart implementations, or bindings yet. (as far as I can find).

But it seems that argon2_ffi already supports all platforms.

**Comment by hpoul** [comment]
Ah okay, removed that from the readme.. I've made argon2_ffi for it, and am actively trying it with https://authpass.app
